### ISSUE TITLE
Disconnect throws an error

### ISSUE THREAD

**Issue by Sud-Puth** [mintuz/BB8-Commander#12]
When I do 

> node index.js disconnect

I get the following

```
module.js:328
    throw err;
    ^

Error: Cannot find module '/BB8-Commander/commands/./commands/disconnect'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /BB8-Commander/libs/execute-command.js:8:7
    at /BB8-Commander/node_modules/sphero/lib/sphero.js:130:7
    at /BB8-Commander/node_modules/sphero/lib/adaptors/ble.js:316:5
    at /BB8-Commander/node_modules/sphero/lib/adaptors/ble.js:168:13
    at Characteristic.<anonymous> (/BB8-Commander/node_modules/noble/lib/characteristic.js:91:7)
    at Characteristic.g (events.js:260:16)
```

**Comment by mintuz** [comment]
@Sud-Puth this should be fixed now if you want to retry it.

**Comment by Sud-Puth** [comment]
@mintuz - The log statement was failing and I just requested a pull request (#14) to fix that but also looks like the BB-8 officially doesn't support disconnect command cause even after issuing the disconnect command, and I issue another command, it just parses that. 
Did you try the command yourself ?
